name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip3 install --user --upgrade buildozer cython==0.29.36
          sudo apt-get install -y scons libgstreamer1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav libgstreamer-plugins-base1.0-dev libasound2-dev libjack-jackd2-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev pkg-config libportaudio2 libasound2-dev

      - name: Build with Buildozer
        run: buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: bin/*.apk
          

